My second homework
dhanur350/Homework2 pull request #1
Opened 2020-10-29 17:54 UTC by dhanur350

Please Check the homework , do find if any mistakes I've done

2020-10-29 18:08 UTC, igniteacademy requested changes

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +	<u style="color: blue;">Link to my portfolio</u> <!--Should be <a> tag-->
Why we using <u> tag here ?
Definition of you tag: The <u> tag represents some text that is unarticulated and styled differently from normal text.
And this is supposed to be linke to your portfolio. PLease use <a> tag

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +	<ol> <!--Use tab or two spaces for styling code--> <!--I didn't get it what you are trying to say here???-->
Code style: Missing tab

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +	<li>Javascript</li>
Code style: Missing tab

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +		</ol>
Code style: end tag </ol> should be on the same level as open tag <ol>

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +		<thead>
Code style: Missing tab

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +		<th colspan="2">Period</th>
Code style: Missing tab

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +		<tr>
Code style: Missing tab

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +		</tr>
Code style: Close tag should be on the same level as open tag

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +		<tr>
again code style

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +	</div>
again code style: close tag should be the same level as open tag

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +	</main>
again code style: close tag should be the same level as open tag

2020-10-29 18:08 UTC, igniteacademy commented on 1_base_table.html
> +</body>
again code style: close tag should be the same level as open tag

2020-10-30 00:39 UTC, dhanur350 commented on 1_base_table.html
> +	<u style="color: blue;">Link to my portfolio</u> <!--Should be <a> tag-->
Mam here in the homework you did underline in the sentence so did I..

2020-10-30 12:58 UTC, igniteacademy commented on 1_base_table.html
> +	<u style="color: blue;">Link to my portfolio</u> <!--Should be <a> tag-->
I didnt get what do you mean by underline. U tag is for styling. And in homework you have link to your protfolio so you can click it and go to any other website.

2020-11-01 13:31 UTC, merged